### ISSUE TITLE
What is the reason for fork?

### ISSUE THREAD

**Issue by Ughuuu** [foxssake/noray#45]
I see both repo's natty and noray were written by you. Why is there a fork for the two? Can they not share the same code?

**Comment by elementbound** [comment]
The original project was natty, which had a much larger scope ( accounts, friends, lobbies, chat, etc. ). After a while, I decided to just focus on the connection orchestration, since that was the only thing really required for building online games.
So currently noray is the project actively used and maintained, while I figure out where to go with natty.

As for the code share, noray is built on the same code-base as natty, but a lot of things were either removed or shuffled around. Also natty uses [nlon](https://elementbound.github.io/nlon/), while noray uses its own, much simpler protocol.
